-- DROP TABLES (se existirem)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE t_usuario CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN -- ORA-00942: tabela ou view não existe
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE t_agendamento CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE t_rota CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE t_emergencia CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE t_caminhao CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE t_recipiente CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- DROP SEQUENCES (se existirem)
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AUTOMATIC_T_USUARIO';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN -- ORA-02289: sequência não existe
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AUTOMATIC_T_AGENDAMENTO';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AUTOMATIC_T_ROTA';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AUTOMATIC_T_EMERGENCIA';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AUTOMATIC_T_CAMINHAO';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AUTOMATIC_T_RECIPIENTE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/


CREATE TABLE t_recipiente  (
    id_recipiente   INTEGER NOT NULL PRIMARY KEY,
    max_capacidade  INTEGER NOT NULL,
    atual_nvl       INTEGER NOT NULL,
    status          VARCHAR2(20) NOT NULL,
    ultima_att      TIMESTAMP NOT NULL,
    latitude_recip  FLOAT NOT NULL,
    longitude_recip FLOAT NOT NULL
);

CREATE SEQUENCE SEQ_AUTOMATIC_T_RECIPIENTE
START WITH 1
INCREMENT BY 1 NOCACHE
NOCYCLE;
