CREATE TABLE IF NOT EXISTS t_caminhao (
    id_caminhao   INTEGER NOT NULL PRIMARY KEY,
    ds_placa      VARCHAR2(7 CHAR) NOT NULL,
    ds_capacidade INTEGER NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS SEQ_AUTOMATIC_T_CAMINHAO
START WITH 1
INCREMENT BY 1 NOCACHE
NOCYCLE;
