CREATE SEQUENCE SEQ_AUTOMATIC_T_USUARIO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


CREATE TABLE T_USUARIO (
  USUARIO_ID INTEGER DEFAULT SEQ_USUARIOS.NEXTVAL NOT NULL PRIMARY KEY,
  NOME VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR(100) UNIQUE NOT NULL,
  SENHA VARCHAR(100) NOT NULL,
  ROLE VARCHAR2(50) DEFAULT 'USER'
);
