name: CI/CD

on:
  push:
    branches: [ main ]

env:
  IMAGE: barbaramalmeida/gestao-residuos

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - id: meta
        run: echo "::set-output name=tag::${{ github.run_id }}"
      - uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:dev-${{ steps.meta.outputs.tag }}
            ${{ env.IMAGE }}:prod-${{ steps.meta.outputs.tag }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to ACI Dev
        run: |
          az container create \
            --resource-group rg-gestao-dev \
            --name gestao-residuos-dev \
            --image ${{ env.IMAGE }}:dev-${{ needs.build-and-push.outputs.tag }} \
            --dns-name-label gestao-residuos-dev \
            --ports 8080 --cpu 1 --memory 1.5 \
            --restart-policy OnFailure

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to ACI Prod
        run: |
          az container create \
            --resource-group rg-gestao-prod \
            --name gestao-residuos-prod \
            --image ${{ env.IMAGE }}:prod-${{ needs.build-and-push.outputs.tag }} \
            --dns-name-label gestao-residuos-prod \
            --ports 8080 --cpu 1 --memory 1.5 \
            --restart-policy OnFailure
